### ISSUE TITLE
registerWorker() performance over WAN

### ISSUE THREAD

**Issue by nponeccop** [iarna/abraxas#18]
From my tests it seems that getting each task requires a RTT. So if there is 50 ms of round trip time between a worker and `gearmand`, it can never perform more than 1000 / 50 = 20 tasks per second.

Is there a way to send multiple `GRAB_JOB_UNIQ` without waiting for `JOB_ASSIGN_UNIQ` in between? Does `gearmand` support this kind of pipelining?

**Comment by amv** [comment]
I remember @iarna blogging about the fact that the gearman protocol allows multiple concurrent GRAB_JOB's even for a single connection.

I have understood that this is why the abraxas registerWorker has the maxJobs option to limit how many GRAB_JOB calls it should concurrently send. Haven't tested that in practice though.

If you are running in an event loop environment like node.js, you could also manually register several worker objects to run in parallel with their individual connections.

**Comment by iarna** [comment]
Yes, that's right, that's exactly what `maxJobs` does, check out https://github.com/iarna/abraxas/blob/master/example/load.js for an example of using it.

https://github.com/iarna/abraxas/blob/master/example/multicore.js has an example of using `cluster` to spread work across CPU cores too.

**Comment by nponeccop** [comment]
`abraxas` supports concurrent `JOB_ASSIGN_UNIQ` but not concurrent 'JOB_GRAB_UNIQ'

The sequence for 2 `maxJobs` is "grab-assign-grab-assign" instead of "grab-grab-assign-assign" and it harms performance on connections with large bandwidth-latency product.

For example, 

https://github.com/iarna/abraxas/blob/ca73cf74c4ad04a5380fbaa4328f756a629733e7/worker.js#L32

Should it be `while` instead of `if`?

**Comment by iarna** [comment]
@nponeccop Ah, I see what you're saying. 

It will totally handle multiple concurrent jobs on a single connection, because it `PRE_SLEEP`s after accepting a job if there is room for more work. But that means that the concurrent job network flow looks like:

(assuming maxJobs = 2)
```
-> PRE_SLEEP
<- NOOP
-> GRAB_JOB_UNIQ
<- ASSIGN_JOB_UNIQ
-> PRE_SEEP
<- NOOP
-> GRAB_JOB_UNIQ
<- ASSIGN_JOB_UNIQ
-> WORK_COMPLETE
-> PRE_SLEEP
-> WORK_COMPLETE
```

Where as you would like:

```
-> PRE_SLEEP
<- NOOP
-> GRAB_JOB_UNIQ
-> GRAB_JOB_UNIQ
<- ASSIGN_JOB_UNIQ
<- ASSIGN_JOB_UNIQ
-> WORK_COMPLETE
-> PRE_SLEEP
-> WORK_COMPLETE
```

**Comment by iarna** [comment]
If we just change the `if` to a `while`, it looks like it would mostly be ideal. The  only "issue" I would anticipate would be an extraneous `PRE_SLEEP`– and that's A) easy to guard and B) maybe not an issue?

```
-> PRE_SLEEP
<- NOOP
-> GRAB_JOB_UNIQ
-> GRAB_JOB_UNIQ
<- ASSIGN_JOB_UNIQ
<- NO_JOB
-> PRE_SLEEP
-> WORK_COMPLETE
-> PRE_SLEEP
-> WORK_COMPLETE
```

**Comment by nponeccop** [comment]
@iarna Yes it is correct. However, waiting for `NOOP` is a different issue #19 and could be fixed too if proved useful.

**Comment by iarna** [comment]
If you wanted to put together PRs, I'd take them, if not, I will likely get to these, though I'm not sure on what timeline at the moment.

**Comment by nponeccop** [comment]
@streamcode9 and I implemented a benchmark in Typescript:

[benchmark/app.ts](https://github.com/streamcode9/abraxas/blob/2b6fbdb1eb971ad344235001afe7ef8ea41f57e4/benchmark/abraxas-benchmark/app.ts)

And it shows that if `if` is replaced by `while`, and both the worker and the client are connected by WAN with 150 ms latency, the performance is increased twofold. I'll show few whisker charts later.

How do we clean the commit so it can be accepted as a PR? Now the repo contains Typescript type declarations. Is it ok? Or it's better to submit the compiled javascript version of the benchmark? Or should we submit the `while` PR separately from the bench?

The change of the library code is minimal: [worker.js](https://github.com/streamcode9/abraxas/commit/2b6fbdb1eb971ad344235001afe7ef8ea41f57e4#diff-8a5b5909f5b3ce1a25a1c499ab30da2c)

**Comment by iarna** [comment]
oh wow, that's super cool... I'd prefer the PR by itself for just the code change if that's not too much work.

**Comment by nponeccop** [comment]
Is there any reason why #24 isn't merged? It's just the code change

**Comment by iarna** [comment]
I didn't see it =D
